[package]
name = "stateless-bitcoin-l2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bitcoincore-rpc = "0.19.0"
bls-signatures = "0.15.0"
hex-literal = "0.4.1"
serde = "1.0.215"
sha2 = "0.10.8"
