[package]
name = "stateless-bitcoin-l2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bitcoincore-rpc = "0.19.0"
blsful = "2.5.7"
hex-literal = "0.4.1"
indexmap = "2.6.0"
rs_merkle = "1.4.2"
serde = "1.0.215"
sha2 = "0.10.8"
thiserror = "2.0.3"
